spring.application.name=wso2-server
server.port=8093
spring.datasource.url=jdbc:sqlite:wso2-server/src/main/resources/database.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.sql.init.mode=never
jwt.secret=learning-only-secret-key-with-at-least-32-bytes
jwt.expiration-ms=3600000
