spring.application.name=OpenFeign
server.port=8091

spring.cloud.discovery.client.simple.instances.posts-client[0].uri=https://dummyjson.com
spring.cloud.discovery.client.simple.instances.posts-client[1].uri=http://localhost:8001
spring.cloud.discovery.client.simple.instances.posts-client[2].uri=http://localhost:8002

resilience4j.retry.configs.default.maxAttempts=3
resilience4j.retry.configs.default.waitDuration=500ms
