spring.application.name=wso2-client
server.port=8092
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

wso2.token-url=https://localhost:9443/oauth2/token
wso2.api-url=https://localhost:8243/dummy-shit/3.0.0/posts
wso2.consumer-key=${WSO2_CONSUMER_KEY:Nwtofak0QCXJB876LJvi5snlG8ka}
wso2.consumer-secret=${WSO2_CONSUMER_SECRET:i5udUPePsdIJITu0FYk0LF9gm1sa}
