spring.application.name=LoadBalancer
server.port=8080

# Service discovery configuration for myservice
spring.cloud.discovery.client.simple.instances.myservice[0].uri=http://localhost:8001
spring.cloud.discovery.client.simple.instances.myservice[1].uri=http://localhost:8002