openapi: 3.0.1
info:
  title: foreach
  description: API Definition of foreach
  version: 1.0.0
servers:
  - url: http://localhost:8290/foreach
  - url: https://localhost:8253/foreach
paths:
  /:
    get:
      responses:
        default:
          description: Default response
